/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AdminHitungGaji extends javax.swing.JFrame {

    /**
     * Creates new form AdminHitungGaji
     */
    public AdminHitungGaji() {
        this.setTitle("Hitung Gaji");
        initComponents();
    }
    
    public void ceknip(){
         try {
            Connection con = Koneksi.configDB(); //buat koneksi
            Statement s = con.createStatement(); //buat statement untuk menampung query sql

            String sql = "SELECT * FROM karyawan where nip= '" + txtnip.getText() + "'"; //query sql untuk mengecek nip
            ResultSet r = s.executeQuery(sql); //hasil dari query swl diatas

            if (r.next()) {
                JOptionPane.showMessageDialog(this, "NIP benar");

            } else {
                JOptionPane.showMessageDialog(this, "NIP salah");
                
            }
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
    }
    
     public void ceknama(){
         try {
            Connection con = Koneksi.configDB(); //buat koneksi
            Statement s = con.createStatement(); //buat statement untuk menampung query sql

            String sql = "SELECT * FROM karyawan where nama= '" + txtnama.getText() + "'"; //query sql untuk mengecek nama
            ResultSet r = s.executeQuery(sql); //hasil dari query swl diatas

            if (r.next()) {
                JOptionPane.showMessageDialog(this, "Nama benar");

            } else {
                JOptionPane.showMessageDialog(this, "Nama salah");
                
            }
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
    }
     
      public void cekjabatan(){
         try {
            Connection con = Koneksi.configDB(); //buat koneksi
            Statement s = con.createStatement(); //buat statement untuk menampung query sql

            String sql = "SELECT * FROM karyawan where jabatan= '" + txtjabatan.getText() + "'"; //query sql untuk mengecek jabatan
            ResultSet r = s.executeQuery(sql); //hasil dari query swl diatas

            if (r.next()) {
                JOptionPane.showMessageDialog(this, "Jabatan benar");

            } else {
                JOptionPane.showMessageDialog(this, "Jabatan salah");
                
            }
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnip = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        gajipokok = new javax.swing.JTextField();
        tunjangan = new javax.swing.JTextField();
        lembur = new javax.swing.JTextField();
        totpemasukan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bpjs = new javax.swing.JTextField();
        pajak = new javax.swing.JTextField();
        totpengurangan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tombolhitung = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        gajibersih = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(232, 250, 224));

        txtnip.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtnip.setForeground(new java.awt.Color(69, 183, 183));
        txtnip.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NIP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N
        txtnip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtnipMouseReleased(evt);
            }
        });
        txtnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnipActionPerformed(evt);
            }
        });

        txtnama.setEditable(false);
        txtnama.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtnama.setForeground(new java.awt.Color(69, 183, 183));
        txtnama.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nama", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N
        txtnama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtnamaMouseReleased(evt);
            }
        });
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtjabatan.setEditable(false);
        txtjabatan.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtjabatan.setForeground(new java.awt.Color(69, 183, 183));
        txtjabatan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "jabatan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N
        txtjabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtjabatanMouseReleased(evt);
            }
        });
        txtjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjabatanActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin User 1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin NIP 1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin Jabatan 1.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(69, 183, 183));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hitung Gaji Karyawan");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setFocusable(false);
        jLabel6.setVerifyInputWhenFocusTarget(false);

        jPanel2.setBackground(new java.awt.Color(69, 183, 183));

        jLabel8.setBackground(new java.awt.Color(69, 183, 183));
        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(232, 250, 224));
        jLabel8.setText(" <");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnip)
                    .addComponent(txtnama)
                    .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 260));

        jPanel5.setBackground(new java.awt.Color(232, 250, 224));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 183, 183));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pemasukan");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setFocusable(false);
        jLabel3.setVerifyInputWhenFocusTarget(false);

        gajipokok.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        gajipokok.setForeground(new java.awt.Color(69, 183, 183));
        gajipokok.setBorder(null);
        gajipokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajipokokActionPerformed(evt);
            }
        });

        tunjangan.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tunjangan.setForeground(new java.awt.Color(69, 183, 183));
        tunjangan.setBorder(null);
        tunjangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjanganActionPerformed(evt);
            }
        });

        lembur.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lembur.setForeground(new java.awt.Color(69, 183, 183));
        lembur.setBorder(null);
        lembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemburActionPerformed(evt);
            }
        });

        totpemasukan.setEditable(false);

        jLabel9.setForeground(new java.awt.Color(69, 183, 183));
        jLabel9.setText("Gaji Pokok");

        jLabel10.setForeground(new java.awt.Color(69, 183, 183));
        jLabel10.setText("Tunjangan");

        jLabel11.setForeground(new java.awt.Color(69, 183, 183));
        jLabel11.setText("Lembur");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gajipokok, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(tunjangan)
                            .addComponent(lembur))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(totpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gajipokok, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lembur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(totpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, 220));

        jPanel6.setBackground(new java.awt.Color(232, 250, 224));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(69, 183, 183));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pengurangan");
        jLabel5.setToolTipText("");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setFocusable(false);
        jLabel5.setVerifyInputWhenFocusTarget(false);

        bpjs.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bpjs.setForeground(new java.awt.Color(69, 183, 183));
        bpjs.setBorder(null);
        bpjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpjsActionPerformed(evt);
            }
        });

        pajak.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pajak.setForeground(new java.awt.Color(69, 183, 183));
        pajak.setBorder(null);
        pajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pajakActionPerformed(evt);
            }
        });

        totpengurangan.setEditable(false);

        jLabel12.setForeground(new java.awt.Color(69, 183, 183));
        jLabel12.setText("Pajak");

        jLabel13.setForeground(new java.awt.Color(69, 183, 183));
        jLabel13.setText("BPJS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(totpengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pajak, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bpjs, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpjs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pajak, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(totpengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 300, 220));

        jPanel7.setBackground(new java.awt.Color(232, 250, 224));

        tombolhitung.setBackground(new java.awt.Color(69, 183, 183));
        tombolhitung.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tombolhitung.setForeground(new java.awt.Color(232, 250, 224));
        tombolhitung.setText("Hitung");
        tombolhitung.setBorder(null);
        tombolhitung.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tombolhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhitungActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(69, 183, 183));
        jLabel7.setText("Gaji Bersih");

        gajibersih.setEditable(false);

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(tombolhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(136, 136, 136))
                            .addComponent(gajibersih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombolhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gajibersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 600, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjabatanActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnipActionPerformed

    private void gajipokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajipokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gajipokokActionPerformed

    private void tunjanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunjanganActionPerformed

    private void lemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lemburActionPerformed

    private void bpjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpjsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpjsActionPerformed

    private void pajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pajakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pajakActionPerformed

    private void tombolhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhitungActionPerformed
        //jika data filed kosong
        if (txtnama.getText().isEmpty() || txtjabatan.getText().isEmpty() || txtnip.getText().isEmpty() || gajipokok.getText().isEmpty()
                || tunjangan.getText().isEmpty() || lembur.getText().isEmpty() || bpjs.getText().isEmpty() || pajak.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong !!!!");
        }
        
        //deklarasi variabel
        double gaji_pokok = Double.parseDouble(gajipokok.getText()),
                tunjangan = Double.parseDouble(this.tunjangan.getText()),
                lembur =  Double.parseDouble(this.lembur.getText()),
                bpjs = Double.parseDouble(this.bpjs.getText()),
                pajak = Double.parseDouble(this.pajak.getText()),
                total_pemasukan,total_pengurangan,gaji_bersih;
        
        //hitung total pemasukan 
        total_pemasukan = gaji_pokok + tunjangan + lembur;
        totpemasukan.setText(""+ total_pemasukan);
        
        //hitung total pengeluaran
        total_pengurangan= bpjs + pajak;
        totpengurangan.setText("" + total_pengurangan);
        
        //hitung total gaji
        gaji_bersih = total_pemasukan - total_pengurangan;
        gajibersih.setText("" + gaji_bersih);
        
        
        //menampilkan data ke form
        output.setText("NIP\t : " + txtnip.getText() + "\nNama\t : " + txtnama.getText() + 
                "\nJabatan\t : " + txtjabatan.getText() + "\nPemasukan\t : Rp " + total_pemasukan +
                "\nPengurangan\t : Rp " + total_pengurangan + "\nGaji Bersih\t : Rp " + gaji_bersih);
        
       
        //memasukan data ke dalam database
           //menyimpan data yang telah diinput pada form
        try {

            /**
             * membuat variabel sql untuk memasukan data yang telah diinput ke
             * database perintah input data sama seperti di command mysql
             * menggunakan perintah INSERT INTO DATABASES VALUE
             */
            String sql = "INSERT INTO gaji_karyawan VALUES ('" + txtnip.getText() + "','" + txtnama.getText() + "','" + txtjabatan.getText() + "','" + total_pemasukan + "','" + total_pengurangan+ "','" + gaji_bersih +  "')";

          

            /**
             * *
             * membuat koneksi ke database ini harus dibuat dimasing-masing
             * event Konfig = class java yang berisi konfigurasi koneksi ke
             * database configDB() merupakan fungsi dari kelas Konfig
             */
            java.sql.Connection conn = (Connection) Koneksi.configDB();

            //membuat statement untuk merepresentasikan perintah sql setelah terjadi koneksi ke database
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);

            //untuk mengeksekusi statement
            pstm.execute();

            //pesan jika proses penyimpanan berhasil, this untuk memunculkan kotak dialog berada di atas form
            JOptionPane.showMessageDialog(this, "Data berhasi diunggah ke database");
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_tombolhitungActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        //untuk kembali ke halaman awal 
        AdminPilihMenu KL = new AdminPilihMenu();
        KL.setVisible(true);
        KL.pack();
        KL.setLocationRelativeTo(null);
        KL.setDefaultCloseOperation(KL.EXIT_ON_CLOSE);
        dispose(); //menutup jendela
    }//GEN-LAST:event_jLabel8MouseClicked

    private void txtnipMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnipMouseReleased
        ceknip();
         try {
            Connection con = Koneksi.configDB(); //buat koneksi
            Statement s = con.createStatement(); //buat statement untuk menampung query sql

            String sql = "SELECT * FROM karyawan where nip= '" + txtnip.getText() + "'"; //query sql untuk mendapatkan id dan password
            ResultSet r = s.executeQuery(sql); //hasil dari query swl diatas

            if (r.next()) {
                txtnama.setText(r.getString("nama"));
                txtjabatan.setText(r.getString("jabatan"));
            } else {
                JOptionPane.showMessageDialog(this, "NIP tidak terdaftar");
                
            }
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_txtnipMouseReleased

    private void txtnamaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamaMouseReleased
        ceknama();
    }//GEN-LAST:event_txtnamaMouseReleased

    private void txtjabatanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjabatanMouseReleased
        cekjabatan();
    }//GEN-LAST:event_txtjabatanMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHitungGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHitungGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHitungGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHitungGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHitungGaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bpjs;
    private javax.swing.JTextField gajibersih;
    private javax.swing.JTextField gajipokok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lembur;
    private javax.swing.JTextArea output;
    private javax.swing.JTextField pajak;
    private javax.swing.JButton tombolhitung;
    private javax.swing.JTextField totpemasukan;
    private javax.swing.JTextField totpengurangan;
    private javax.swing.JTextField tunjangan;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    // End of variables declaration//GEN-END:variables
}
