/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class AdminCRUD extends javax.swing.JFrame {

    //konstruktor
    public AdminCRUD() {
        this.setTitle("Data Karyawan");
        initComponents();
        txtnama.setEditable(true);
        txtsearch.setEditable(true);
        TampilakanData();
    }

    //untuk mengosongkan form
    private void KosongkanForm() {
        txtnama.setText(null);
        txtalamat.setText(null);
        txtemail.setText(null);
        txtid.setText(null);
        txtpassword.setText(null);
        txtjabatan.setText(null);
        txttelepon.setText(null);
        txtnip.setText(null);
//        txtgaji.setText(null);
    }

    //menampilkan data dari database ke tabel
    private void TampilakanData() {

        //membuat objek tabel
        DefaultTableModel model = new DefaultTableModel();

        //membuat kolom dan memberi judul pada kolom tabel
        model.addColumn("No.");
        model.addColumn("Nama");
        model.addColumn("NIP");
        model.addColumn("Jabatan");
        model.addColumn("Alamat");
        model.addColumn("Email");
        model.addColumn("No.Telp");
        model.addColumn("ID");
        model.addColumn("Password");
        

        //membuat koneksi menampilkan data dari database ke tabel
        try {

            //no digunakan sebagai index untuk looping array
            int no = 1;

            //perintah sql untuk menampilkan data tabel
            String sql = "SELECT * FROM karyawan";

            /**
             *
             * membuat koneksi ke database ini harus dibuat dimasing-masing
             * event Konfig = class java yang berisi konfigurasi koneksi ke
             * database configDB() merupakan fungsi dari kelas Konfig
             *
             */
            java.sql.Connection conn = (Connection) Koneksi.configDB();

            //membuat statement untuk merepresentasikan perintah sql setelah terjadi koneksi ke database
            java.sql.Statement stm = conn.createStatement();

            //resultset adalah hasil dari statement
            java.sql.ResultSet res = stm.executeQuery(sql);

            //looping untuk memanggil tiap filed dalam database untuk dimasukan ke dalam tabel
            while (res.next()) {
                /**
                 * *
                 * res.getString(1) = nik res.getString(2) = nama
                 * res.getString(3) = jabatan res.getString(4) = alamat
                 * res.getString(5) = email res.getString(6) = notelpon
                 */
                model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3),
                    res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8)});
            }

            //data di atas dimasukan ke tabel karyawan
            tabelkaryawan.setModel(model);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tombolsimpan = new javax.swing.JButton();
        txtnip = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tombolhapus = new javax.swing.JButton();
        tomboledit = new javax.swing.JButton();
        tombollogoutadmin = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelkaryawan = new javax.swing.JTable();
        tombolbatal = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        tombolsearch = new javax.swing.JButton();
        tombolreset = new javax.swing.JButton();
        tombolkback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(232, 250, 224));
        jPanel2.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(69, 183, 183));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data Karyawan");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtnama.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtnama.setForeground(new java.awt.Color(69, 183, 183));
        txtnama.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nama", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin User 1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin NIP 1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin Jabatan 1.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin Alamat 1.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin Mail.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin Nomor.png"))); // NOI18N

        tombolsimpan.setBackground(new java.awt.Color(69, 183, 183));
        tombolsimpan.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        tombolsimpan.setForeground(new java.awt.Color(232, 250, 224));
        tombolsimpan.setText("Simpan");
        tombolsimpan.setBorder(null);
        tombolsimpan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tombolsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsimpanActionPerformed(evt);
            }
        });

        txtnip.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtnip.setForeground(new java.awt.Color(69, 183, 183));
        txtnip.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NIP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N

        txtjabatan.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtjabatan.setForeground(new java.awt.Color(69, 183, 183));
        txtjabatan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jabatan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N

        txtalamat.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtalamat.setForeground(new java.awt.Color(69, 183, 183));
        txtalamat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alamat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N

        txtemail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtemail.setForeground(new java.awt.Color(69, 183, 183));
        txtemail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N

        txttelepon.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txttelepon.setForeground(new java.awt.Color(69, 183, 183));
        txttelepon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nomor telp.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N
        txttelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleponActionPerformed(evt);
            }
        });
        txttelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtteleponKeyTyped(evt);
            }
        });

        txtid.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtid.setForeground(new java.awt.Color(69, 183, 183));
        txtid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtpassword.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(69, 183, 183));
        txtpassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(69, 183, 183))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin ID 1.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Admin PW 1.png"))); // NOI18N

        tombolhapus.setBackground(new java.awt.Color(69, 183, 183));
        tombolhapus.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        tombolhapus.setForeground(new java.awt.Color(232, 250, 224));
        tombolhapus.setText("Hapus");
        tombolhapus.setBorder(null);
        tombolhapus.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tombolhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusActionPerformed(evt);
            }
        });

        tomboledit.setBackground(new java.awt.Color(69, 183, 183));
        tomboledit.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        tomboledit.setForeground(new java.awt.Color(232, 250, 224));
        tomboledit.setText("Edit");
        tomboledit.setBorder(null);
        tomboledit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tomboledit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboleditActionPerformed(evt);
            }
        });

        tombollogoutadmin.setBackground(new java.awt.Color(232, 250, 224));
        tombollogoutadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/log-out 1.png"))); // NOI18N
        tombollogoutadmin.setBorder(null);
        tombollogoutadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombollogoutadminActionPerformed(evt);
            }
        });

        tabelkaryawan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelkaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelkaryawanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelkaryawan);

        tombolbatal.setBackground(new java.awt.Color(69, 183, 183));
        tombolbatal.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        tombolbatal.setForeground(new java.awt.Color(232, 250, 224));
        tombolbatal.setText("Batal");
        tombolbatal.setBorder(null);
        tombolbatal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tombolbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbatalActionPerformed(evt);
            }
        });

        txtsearch.setForeground(new java.awt.Color(69, 183, 183));
        txtsearch.setText("   Serach By NIP");
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchMouseClicked(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        tombolsearch.setBackground(new java.awt.Color(69, 183, 183));
        tombolsearch.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tombolsearch.setForeground(new java.awt.Color(232, 250, 224));
        tombolsearch.setText("Search");
        tombolsearch.setBorder(null);
        tombolsearch.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tombolsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsearchActionPerformed(evt);
            }
        });

        tombolreset.setBackground(new java.awt.Color(69, 183, 183));
        tombolreset.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        tombolreset.setForeground(new java.awt.Color(232, 250, 224));
        tombolreset.setText("Reset");
        tombolreset.setBorder(null);
        tombolreset.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tombolreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolresetActionPerformed(evt);
            }
        });

        tombolkback.setBackground(new java.awt.Color(69, 183, 183));
        tombolkback.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        tombolkback.setForeground(new java.awt.Color(232, 250, 224));
        tombolkback.setText("<");
        tombolkback.setBorder(null);
        tombolkback.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tombolkback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tombolkback, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tombollogoutadmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tomboledit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tombolreset, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tombolbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tombolhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tombolsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnama))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnip))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtpassword))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txttelepon))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtalamat))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(tombolsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(54, 54, 54))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolkback, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtjabatan)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(txtemail)
                            .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(txtid)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombollogoutadmin)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tombolbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tombolhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tomboledit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tombolreset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombollogoutadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombollogoutadminActionPerformed
        //keluar dari jendela
        dispose();
    }//GEN-LAST:event_tombollogoutadminActionPerformed

    private void tombolsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsimpanActionPerformed
        //menyimpan data yang telah diinput pada form
        try {

            /**
             * membuat variabel sql untuk memasukan data yang telah diinput ke
             * database perintah input data sama seperti di command mysql
             * menggunakan perintah INSERT INTO DATABASES VALUE
             */
            String sql = "INSERT INTO karyawan VALUES ('" + txtnama.getText() + "','" + txtnip.getText() + "','" + txtjabatan.getText() + "','" + txtalamat.getText() + "','" + txtemail.getText() + "','" + txttelepon.getText() + "','" + txtid.getText() + "','" + txtpassword.getText() +  "')";

            //membuat kondisi jika ada filed form yang belum terisi maka akan ada pesan error
            if (txtnama.getText().equals("") || txtnip.getText().equals("") || txtjabatan.getText().equals("")
                    || txtalamat.getText().equals("") || txtemail.getText().equals("") || txttelepon.getText().equals("") || txtid.getText().equals("")
                    || txtpassword.getText().equals("")) {

                //this untuk pesan error berada di depan form
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
                return;
            }

            /**
             * *
             * membuat koneksi ke database ini harus dibuat dimasing-masing
             * event Konfig = class java yang berisi konfigurasi koneksi ke
             * database configDB() merupakan fungsi dari kelas Konfig
             */
            java.sql.Connection conn = (Connection) Koneksi.configDB();

            //membuat statement untuk merepresentasikan perintah sql setelah terjadi koneksi ke database
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);

            //untuk mengeksekusi statement
            pstm.execute();

            //pesan jika proses penyimpanan berhasil, this untuk memunculkan kotak dialog berada di atas form
            JOptionPane.showMessageDialog(this, "Success..");

            //menampilkan data ke tabel dari database
            TampilakanData();

            //mengosongkan form untuk memulai input baru
            KosongkanForm();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_tombolsimpanActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleponActionPerformed

    }//GEN-LAST:event_txtteleponActionPerformed

    private void txtteleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteleponKeyTyped
        //untuk mengatur agar inputan du No Telpon hanya dapat berupa angka saja
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter)))
            evt.consume();
    }//GEN-LAST:event_txtteleponKeyTyped

    private void tombolbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbatalActionPerformed
        KosongkanForm();
        TampilakanData();
    }//GEN-LAST:event_tombolbatalActionPerformed

    private void tombolhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusActionPerformed
        try {
            //membuat sql untuk menghapus
            String sqlHapus = "DELETE FROM karyawan WHERE nip= '" + txtnip.getText() + "'";

            //membuat connection
            java.sql.Connection conn = (Connection) Koneksi.configDB();

            //membuat statment
            java.sql.PreparedStatement pstm = conn.prepareStatement(sqlHapus);

            //eksekusi statement
            pstm.execute();
            
            
             //membuat kondisi jika ada filed form yang belum terisi maka akan ada pesan error
            if (txtnama.getText().equals("") || txtnip.getText().equals("") || txtjabatan.getText().equals("")
                    || txtalamat.getText().equals("") || txtemail.getText().equals("") || txttelepon.getText().equals("") || txtid.getText().equals("")
                    || txtpassword.getText().equals("")) {

                //this untuk pesan error berada di depan form
                JOptionPane.showMessageDialog(this, "Hapus gagal!! Data belum dipilih");
                return;
            }

            KosongkanForm();
            TampilakanData();

            //menampilkan pesan berhasil
            JOptionPane.showMessageDialog(this, "Hapus data berhasil..");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal!!!" + e.getMessage());
        }
    }//GEN-LAST:event_tombolhapusActionPerformed

    private void tabelkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelkaryawanMouseClicked
        /**
         * ini untuk menjalankan fungsi edit jadi ketika data telah di input dan
         * masuk ketabel lalu akan dilakukan peng-editan maka kita mengklik data
         * tersebut dan data itu akan kembali lagi ke form untuk disimpan
         */

        //ini untuk edit nik
        int baris = tabelkaryawan.rowAtPoint(evt.getPoint());
        String nama = tabelkaryawan.getValueAt(baris, 1).toString();
        txtnama.setText(nama);

        //ini untuk edit nama
        String nip = tabelkaryawan.getValueAt(baris, 2).toString();
        txtnip.setText(nip);

        //ini untuk edit jabatan
        String jabatan = tabelkaryawan.getValueAt(baris, 3).toString();
        txtjabatan.setText(jabatan);

        //ini untuk edit alamat
        String alamat = tabelkaryawan.getValueAt(baris, 4).toString();
        txtalamat.setText(alamat);

        //ini untuk edit email
        String email = tabelkaryawan.getValueAt(baris, 5).toString();
        txtemail.setText(email);

        //ini untuk edit telpon
        String notelpon = tabelkaryawan.getValueAt(baris, 6).toString();
        txttelepon.setText(notelpon);

        //ini untuk edit id
        String id = tabelkaryawan.getValueAt(baris, 7).toString();
        txtid.setText(id);

        //ini untuk edit password
        String password = tabelkaryawan.getValueAt(baris, 8).toString();
        txtpassword.setText(password);

        //ini untuk edit gaji
        String gaji = tabelkaryawan.getValueAt(baris, 9).toString();
        
    }//GEN-LAST:event_tabelkaryawanMouseClicked

    private void tomboleditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboleditActionPerformed
        //untuk menyimpan proses edit dari fungsi method di atas (line 325-356)
        try {

            //melakukan pengeditan dengan syntax sql
            String sql = "UPDATE karyawan SET nama ='" + txtnama.getText() + "',nip='" + txtnip.getText() + "',jabatan='" + txtjabatan.getText() + "',alamat='" + txtalamat.getText() + "',email='" + txtemail.getText() + "',telepon='" + txttelepon.getText() + "',id='" + txtid.getText() + "',password='" + txtpassword.getText()  + "' WHERE nip = '" + txtnip.getText() + "'";

            /**
             * *
             * membuat koneksi ke database ini harus dibuat dimasing-masing
             * event Konfig = class java yang berisi konfigurasi koneksi ke
             * database configDB() merupakan fungsi dari kelas Konfig
             */
            java.sql.Connection conn = (Connection) Koneksi.configDB();

            //membuat statement untuk merepresentasikan perintah sql setelah terjadi koneksi ke database
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);

            //execute akan mengeksekusi si statement
            pstm.execute();
            
            
             //membuat kondisi jika ada filed form yang belum terisi maka akan ada pesan error
            if (txtnama.getText().equals("") || txtnip.getText().equals("") || txtjabatan.getText().equals("")
                    || txtalamat.getText().equals("") || txtemail.getText().equals("") || txttelepon.getText().equals("") || txtid.getText().equals("")
                    || txtpassword.getText().equals("")) {

                //this untuk pesan error berada di depan form
                JOptionPane.showMessageDialog(this, "Edit Gagal !!! Data belum dipilih");
                return;
            }

            
            //menampikan dialog berhasil
            JOptionPane.showMessageDialog(this, "Success...");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        //menampilakn data
        TampilakanData();

        //dan mengsosongkan form 
        KosongkanForm();
    }//GEN-LAST:event_tomboleditActionPerformed

    public void search() {
        //membuat objek tabel
        DefaultTableModel model = new DefaultTableModel();

        //membuat kolom dan memberi judul pada kolom tabel
        model.addColumn("No.");
        model.addColumn("Nama");
        model.addColumn("NIP");
        model.addColumn("Jabatan");
        model.addColumn("Alamat");
        model.addColumn("Email");
        model.addColumn("No.Telp");
        model.addColumn("ID");
        model.addColumn("Password");
        

        //membuat koneksi menampilkan data dari database ke tabel
        try {

            //no digunakan sebagai index untuk looping array
            int no = 1;

            //perintah sql untuk mencari data dari database
            //penggunaan % berpengaruh pada seberapa detail pencarian yang diinginkan
            //jika % diakhir maka akan mencari data sesuai huruf awal yg kita cari lalu diikuti karakter huruf random
            //jika % ada diawal dan akhir maka data yang ingin kita dapatkan akan sama persis dengan apa yang kita masukan
            String sql = "SELECT * FROM karyawan WHERE nip LIKE '%" + txtsearch.getText() + "%'";

            /**
             *
             * membuat koneksi ke database ini harus dibuat dimasing-masing
             * event Konfig = class java yang berisi konfigurasi koneksi ke
             * database configDB() merupakan fungsi dari kelas Konfig
             *
             */
            //membuat koneksi
            java.sql.Connection conn = (Connection) Koneksi.configDB();

            //membuat statement untuk merepresentasikan perintah sql setelah terjadi koneksi ke database
            java.sql.Statement stm = conn.createStatement();

            //resultset adalah hasil dari statement
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            //looping untuk memanggil tiap filed dalam database untuk dimasukan ke dalam tabel
            while (res.next()) {
                //mengambil data dari kolom database sesuai urutan
                model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3),
                    res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8)});
            }
            
             if (txtsearch.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong !!");
                TampilakanData();
            } else {

            }

            //data di atas dimasukan ke tabel karyawan
            tabelkaryawan.setModel(model);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    private void tombolsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsearchActionPerformed
        search();
    }//GEN-LAST:event_tombolsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        //agar saat enter langsung bisa di cari tidak usah menekan tombol search
//        String key = txtsearch.getText();
//        if (key != "") {
//            search();
//        }else{
//            TampilakanData();
//        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void tombolresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolresetActionPerformed
      //untuk menghapus semua isi dalam tabel
      tabelkaryawan.setModel(new DefaultTableModel(null, new String[]{"No", "Nama", "NIP", "Jabatan", "Alamat", "Email", "No.Telp", "ID", "Password", "Gaji"}));

    }//GEN-LAST:event_tombolresetActionPerformed

    private void txtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseClicked
        txtsearch.setText(null);
    }//GEN-LAST:event_txtsearchMouseClicked

    private void tombolkbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkbackActionPerformed
        //untuk kembali ke halaman awal 
        AdminPilihMenu KL = new AdminPilihMenu();
        KL.setVisible(true);
        KL.pack();
        KL.setLocationRelativeTo(null);
        KL.setDefaultCloseOperation(KL.EXIT_ON_CLOSE);
        dispose(); //menutup jendela
    }//GEN-LAST:event_tombolkbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelkaryawan;
    private javax.swing.JButton tombolbatal;
    private javax.swing.JButton tomboledit;
    private javax.swing.JButton tombolhapus;
    private javax.swing.JButton tombolkback;
    private javax.swing.JButton tombollogoutadmin;
    private javax.swing.JButton tombolreset;
    private javax.swing.JButton tombolsearch;
    private javax.swing.JButton tombolsimpan;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
