/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ASUS
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tomboladmin = new javax.swing.JButton();
        tombolkaryawan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tampilan Awal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Baground.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tomboladmin.setBackground(new java.awt.Color(69, 183, 183));
        tomboladmin.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        tomboladmin.setForeground(new java.awt.Color(232, 250, 224));
        tomboladmin.setText("Admin");
        tomboladmin.setBorder(null);
        tomboladmin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tomboladmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboladminActionPerformed(evt);
            }
        });
        jPanel1.add(tomboladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 200, 60));

        tombolkaryawan.setBackground(new java.awt.Color(245, 118, 101));
        tombolkaryawan.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        tombolkaryawan.setForeground(new java.awt.Color(232, 250, 224));
        tombolkaryawan.setText("Karyawan");
        tombolkaryawan.setBorder(null);
        tombolkaryawan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tombolkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkaryawanActionPerformed(evt);
            }
        });
        jPanel1.add(tombolkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 200, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        setSize(new java.awt.Dimension(414, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void tomboladminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboladminActionPerformed
        //diarahkan ke halaman login admin
        AdminLogin choose = new AdminLogin();
        choose.setVisible(true);
        choose.pack();
        choose.setLocationRelativeTo(null);
        choose.setDefaultCloseOperation(AdminLogin.EXIT_ON_CLOSE);
        dispose(); //menutup jendela
    }//GEN-LAST:event_tomboladminActionPerformed

    private void tombolkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkaryawanActionPerformed
        //diarahkan ke halaman login karyawan
        KaryawanLogin choose = new KaryawanLogin();
        choose.setVisible(true);
        choose.pack();
        choose.setLocationRelativeTo(null);
        choose.setDefaultCloseOperation(KaryawanLogin.EXIT_ON_CLOSE);
        dispose(); //menutup jendela
    }//GEN-LAST:event_tombolkaryawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tomboladmin;
    private javax.swing.JButton tombolkaryawan;
    // End of variables declaration//GEN-END:variables
}
